Fix luna-service2 usage
:Release Notes:
Since luna-service2 submission 143 from September 2012 ls2 headers
should be included from luna-service2 directory.

:Detailed Notes:
Fixes:
http://gecko.lge.com:8000/Errors/Details/548218

FAILED: CMakeFiles/location.dir/src/lunaIpc/LunaLocationServiceUtil.cpp.o
TOPDIR/BUILD/work/raspberrypi4-webos-linux-gnueabi/com.webos.service.location/1.0.0-98-r2/recipe-sysroot-native/usr/bin/arm-webos-linux-gnueabi/arm-webos-linux-gnueabi-g++ -DUSE_PMLOG_DECLARATION -ITOPDIR/BUILD/work/raspberrypi4-webos-linux-gnueabi/com.webos.service.location/1.0.0-98-r2/git/include -mthumb -mfpu=neon-vfpv4 -mfloat-abi=hard -mcpu=cortex-a7 -fstack-protector-strong  -O2 -D_FORTIFY_SOURCE=2  -Werror=return-type  --sysroot=TOPDIR/BUILD/work/raspberrypi4-webos-linux-gnueabi/com.webos.service.location/1.0.0-98-r2/recipe-sysroot  -O2 -pipe -g -feliminate-unused-debug-types -fmacro-prefix-map=TOPDIR/BUILD/work/raspberrypi4-webos-linux-gnueabi/com.webos.service.location/1.0.0-98-r2=/usr/src/debug/com.webos.service.location/1.0.0-98-r2                      -fdebug-prefix-map=TOPDIR/BUILD/work/raspberrypi4-webos-linux-gnueabi/com.webos.service.location/1.0.0-98-r2=/usr/src/debug/com.webos.service.location/1.0.0-98-r2                      -fdebug-prefix-map=TOPDIR/BUILD/work/raspberrypi4-webos-linux-gnueabi/com.webos.service.location/1.0.0-98-r2/recipe-sysroot=                      -fdebug-prefix-map=TOPDIR/BUILD/work/raspberrypi4-webos-linux-gnueabi/com.webos.service.location/1.0.0-98-r2/recipe-sysroot-native=  -fvisibility-inlines-hidden  -Wall -std=c++11 -DNDEBUG   -ITOPDIR/BUILD/work/raspberrypi4-webos-linux-gnueabi/com.webos.service.location/1.0.0-98-r2/recipe-sysroot/usr/include/glib-2.0 -ITOPDIR/BUILD/work/raspberrypi4-webos-linux-gnueabi/com.webos.service.location/1.0.0-98-r2/recipe-sysroot/usr/lib/glib-2.0/include -pthread -ITOPDIR/BUILD/work/raspberrypi4-webos-linux-gnueabi/com.webos.service.location/1.0.0-98-r2/recipe-sysroot/usr/include/libmount -ITOPDIR/BUILD/work/raspberrypi4-webos-linux-gnueabi/com.webos.service.location/1.0.0-98-r2/recipe-sysroot/usr/include/blkid -ITOPDIR/BUILD/work/raspberrypi4-webos-linux-gnueabi/com.webos.service.location/1.0.0-98-r2/recipe-sysroot/usr/include/glib-2.0 -ITOPDIR/BUILD/work/raspberrypi4-webos-linux-gnueabi/com.webos.service.location/1.0.0-98-r2/recipe-sysroot/usr/lib/glib-2.0/include -ITOPDIR/BUILD/work/raspberrypi4-webos-linux-gnueabi/com.webos.service.location/1.0.0-98-r2/recipe-sysroot/usr/include/glib-2.0 -ITOPDIR/BUILD/work/raspberrypi4-webos-linux-gnueabi/com.webos.service.location/1.0.0-98-r2/recipe-sysroot/usr/lib/glib-2.0/include -pthread -ITOPDIR/BUILD/work/raspberrypi4-webos-linux-gnueabi/com.webos.service.location/1.0.0-98-r2/recipe-sysroot/usr/include/glib-2.0 -ITOPDIR/BUILD/work/raspberrypi4-webos-linux-gnueabi/com.webos.service.location/1.0.0-98-r2/recipe-sysroot/usr/lib/glib-2.0/include -ITOPDIR/BUILD/work/raspberrypi4-webos-linux-gnueabi/com.webos.service.location/1.0.0-98-r2/recipe-sysroot/usr/include/glib-2.0 -ITOPDIR/BUILD/work/raspberrypi4-webos-linux-gnueabi/com.webos.service.location/1.0.0-98-r2/recipe-sysroot/usr/lib/glib-2.0/include -ITOPDIR/BUILD/work/raspberrypi4-webos-linux-gnueabi/com.webos.service.location/1.0.0-98-r2/recipe-sysroot/usr/include/json-c -ITOPDIR/BUILD/work/raspberrypi4-webos-linux-gnueabi/com.webos.service.location/1.0.0-98-r2/recipe-sysroot/usr/include/glib-2.0 -ITOPDIR/BUILD/work/raspberrypi4-webos-linux-gnueabi/com.webos.service.location/1.0.0-98-r2/recipe-sysroot/usr/lib/glib-2.0/include -ITOPDIR/BUILD/work/raspberrypi4-webos-linux-gnueabi/com.webos.service.location/1.0.0-98-r2/recipe-sysroot/usr/include/glib-2.0 -ITOPDIR/BUILD/work/raspberrypi4-webos-linux-gnueabi/com.webos.service.location/1.0.0-98-r2/recipe-sysroot/usr/lib/glib-2.0/include -ITOPDIR/BUILD/work/raspberrypi4-webos-linux-gnueabi/com.webos.service.location/1.0.0-98-r2/recipe-sysroot/usr/include/libxml2 -ITOPDIR/BUILD/work/raspberrypi4-webos-linux-gnueabi/com.webos.service.location/1.0.0-98-r2/recipe-sysroot/usr/include/loc-utils -MD -MT CMakeFiles/location.dir/src/lunaIpc/LunaLocationServiceUtil.cpp.o -MF CMakeFiles/location.dir/src/lunaIpc/LunaLocationServiceUtil.cpp.o.d -o CMakeFiles/location.dir/src/lunaIpc/LunaLocationServiceUtil.cpp.o -c TOPDIR/BUILD/work/raspberrypi4-webos-linux-gnueabi/com.webos.service.location/1.0.0-98-r2/git/src/lunaIpc/LunaLocationServiceUtil.cpp
In file included from TOPDIR/BUILD/work/raspberrypi4-webos-linux-gnueabi/com.webos.service.location/1.0.0-98-r2/git/src/lunaIpc/LunaLocationServiceUtil.cpp:18:
TOPDIR/BUILD/work/raspberrypi4-webos-linux-gnueabi/com.webos.service.location/1.0.0-98-r2/git/include/LunaLocationServiceUtil.h:21:10: fatal error: lunaservice.h: No such file or directory
   21 | #include <lunaservice.h>
      |          ^~~~~~~~~~~~~~~
compilation terminated.

:Testing Performed:
Only build tested.

:QA Notes:
No change to image.

:Issues Addressed:
[WRP-10642] Remove the temporary work around from 2012 from luna-service2 recipe
[WRP-11226] com.webos.service.location: Fix luna-service2 usage
[WRP-10791] CCC: Various build fixes

Change-Id: I9c0b1cf2f797d48babce8e27ba7ffe23396f4fc3
Reviewed-on: http://gpro.lge.com/c/webosose/com.webos.service.location/+/348157
Tested-by: <muralidhar.n@lge.com>
Reviewed-by: <muralidhar.n@lge.com>
(cherry picked from commit 7f9beee4d78aeec213d74843ad277c611feb3b46)
Reviewed-on: http://gpro.lge.com/c/webosose/com.webos.service.location/+/375808